# Generated by Django 3.0.6 on 2020-05-08 07:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 8, 12, 52, 18, 545609)),
        ),
        migrations.CreateModel(
            name='UserSocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.CharField(blank=True, max_length=35)),
                ('website', models.CharField(blank=True, max_length=35)),
                ('twitter', models.CharField(blank=True, max_length=35)),
                ('instagram', models.CharField(blank=True, max_length=35)),
                ('youtube', models.CharField(blank=True, max_length=35)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(blank=True, max_length=100)),
                ('started', models.DateTimeField(blank=True)),
                ('ended', models.DateTimeField(blank=True)),
                ('degree', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
