# Generated by Django 3.0.6 on 2020-05-08 11:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_auto_20200508_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 5, 8, 17, 3, 32, 265430)),
        ),
        migrations.CreateModel(
            name='UserExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime(2020, 5, 8, 17, 3, 32, 266464))),
                ('post', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
