# Generated by Django 3.0.6 on 2020-05-08 15:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200508_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='created_on',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 8, 21, 14, 43, 627639)),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='ended',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='usereducation',
            name='started',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 21, 14, 43, 628669)),
        ),
    ]
