# Generated by Django 3.0.6 on 2020-05-08 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200508_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='created_on',
            field=models.DateField(blank=True, default=datetime.datetime(2020, 5, 8, 21, 44, 30, 932550)),
        ),
        migrations.AlterField(
            model_name='userexperience',
            name='created_on',
            field=models.DateField(default=datetime.datetime(2020, 5, 8, 21, 44, 30, 934592)),
        ),
    ]
